### PR TITLE
RFC: Add optional Serde support for HashMap

### PR DESCRIPTION
**Pull request by adamreichold**
The implementation of `Deserialize` is based on the implementation of `Extend`.

I can of course remove the first commit as it is admittedly unrelated and unnecessary for Serde support, it just felt better working in a code base that starts without Clippy warnings and stays that way.

### CODE REVIEW

**Review by yaleman — APPROVED** [review]
There's a lot of clippy-calming in there as well, but otherwise looks solid

**Comment by adamreichold** [comment]
> There's a lot of clippy-calming in there as well

Indeed. I did put it into it a separate commit and can drop it if you prefer.

**Comment by yaleman** [comment]
Oh no need, just calling it out. I like keeping 📎 happy

**Review by Firstyear — APPROVED** [review]

**Comment by Firstyear** [comment]
This is excellent @adamreichold, thank you very much!

**Pull request merged**
