### PR TITLE
Refactor Branch and Leaf into unions

### PR DESCRIPTION
**Pull request by danyspin97**
Instead of having a Branch and a BranchSimd struct,
use Branch with a Ctrl union containing both the "normal"
branch and the SIMD one. Same thing with Leaf.

### CODE REVIEW

**Review by Firstyear — APPROVED** [review]
All looks good and passes miri! Just need to finish up the simd side, but should be no issues from here! Thanks!

**Comment by danyspin97** [comment]
The simd side compiles too! I have fixed it right before making the PR.

**Review by Firstyear — APPROVED** [review]

**Comment by Firstyear** [comment]
Passes miri and tests with and without simd! I think I accidentally commited in the past, but in src/lib.rs if you uncomment "deny warnings" and re-test and fix those? Or we can just commit and I'll fix the warns.

**Comment by danyspin97** [comment]
There is only one warning:

```
macro_rules! debug_assert_leaf {
    ($x:expr) => {{
        debug_assert!(unsafe { $x.ctrl.a.0.is_leaf() });
    }};
}
```

```
    pub(crate) unsafe fn get_slot_mut_ref<Q: ?Sized>(
        &mut self,
        h: u64,
    ) -> Option<&mut [Datum<K, V>]>
    where
        K: Borrow<Q>,
        Q: Eq,
    {
        debug_assert_leaf!(self);
        leaf_simd_get_slot(self, h)
            .map(|slot_idx| (*self.values[slot_idx].as_mut_ptr()).as_mut_slice())
    }
```

The `unsafe` block in this case is useless, but it's used in all other invocations. It is okay if I allow `unused_unsafe` in `get_slot_mut_ref`?

**Comment by Firstyear** [comment]
You can just remove the unsafe on the fn in this case, since the debug assert contains the unsafe internally (I think).

**Comment by danyspin97** [comment]
I have added the unsafe inside the function instead, removing the warning.

**Pull request merged**
